title: Dylan Momplaisir
description: Personal Portfolio
url: "https://dmomplaisir.github.io"
baseurl: ""

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - README.md
  - .git/
  - .github/
  - .gitignore

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:path/
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/

# Default front matter settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      custom_css: 
        - shared
        - post
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      custom_css: 
        - shared

# Blog settings
permalink: /blog/:year/:month/:day/:title/
paginate: 5
paginate_path: "/blog/page:num/" 