title: Dylan Momplaisir
description: Personal Portfolio
url: "https://dmomplaisir.com"
baseurl: ""

# Theme settings
theme: minima

# Build settings
markdown: kramdown
future: false  # Don't publish posts with future dates
timezone: America/New_York

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - README.md
  - .git/
  - .github/
  - .gitignore
  - vendor/
  - oldsite/
  - Rally/

# Collections
collections:
  pages:
    output: true
    permalink: /:title/
  projects:
    output: true
    permalink: /projects/:path/
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/

# Default front matter settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

# Blog settings
permalink: /blog/:year/:month/:day/:title/
paginate: 5
paginate_path: "/blog/page:num/" 